///kontroll

/*proov = 0
draw_text(0,proov*30,string(proov)+""+string(object_get_name(proov)));
proov++;
draw_text(0,proov*30,string(proov)+""+string(object_get_name(proov)));
proov++;
draw_text(0,proov*30,string(proov)+""+string(object_get_name(proov)));
proov++;
draw_text(0,proov*30,string(proov)+""+string(object_get_name(proov)));
proov++;
draw_text(0,proov*30,string(proov)+""+string(object_get_name(proov)));
proov++;
draw_text(0,proov*30,string(proov)+""+string(object_get_name(proov)));
proov++;
draw_text(0,proov*30,string(proov)+""+string(object_get_name(proov)));
proov++;
draw_text(0,proov*30,string(proov)+""+string(object_get_name(proov)));
proov++;
draw_text(0,proov*30,string(proov)+""+string(object_get_name(proov)));
proov++;
draw_text(0,proov*30,string(proov)+""+string(object_get_name(proov)));
proov++;
draw_text(0,proov*30,string(proov)+""+string(object_get_name(proov)));
proov++;
draw_text(0,proov*30,string(proov)+""+string(object_get_name(proov)));
proov++;
draw_text(0,proov*30,string(proov)+""+string(object_get_name(proov)));
proov++;
draw_text(0,proov*30,string(proov)+""+string(object_get_name(proov)));
proov++;
draw_text(0,proov*30,string(proov)+""+string(object_get_name(proov)));
proov++;
draw_text(0,proov*30,string(proov)+""+string(object_get_name(proov)));
proov++;
draw_text(0,proov*30,string(proov)+""+string(object_get_name(proov)));
proov++;
draw_text(0,proov*30,string(proov)+""+string(object_get_name(proov)));
proov++;
draw_text(0,proov*30,string(proov)+""+string(object_get_name(proov)));
proov++;
draw_text(0,proov*30,string(proov)+""+string(object_get_name(proov)));
proov++;
*/

proov = 0;
show_debug_message(string(proov)+" "+string(object_get_name(proov)));
proov++;
show_debug_message(string(proov)+" "+string(object_get_name(proov)));
proov++;
show_debug_message(string(proov)+" "+string(object_get_name(proov)));
proov++;
show_debug_message(string(proov)+" "+string(object_get_name(proov)));
proov++;
show_debug_message(string(proov)+" "+string(object_get_name(proov)));
proov++;
show_debug_message(string(proov)+" "+string(object_get_name(proov)));
proov++;
show_debug_message(string(proov)+" "+string(object_get_name(proov)));
proov++;
show_debug_message(string(proov)+" "+string(object_get_name(proov)));
proov++;
show_debug_message(string(proov)+" "+string(object_get_name(proov)));
proov++;
show_debug_message(string(proov)+" "+string(object_get_name(proov)));
proov++;
show_debug_message(string(proov)+" "+string(object_get_name(proov)));
proov++;
show_debug_message(string(proov)+" "+string(object_get_name(proov)));
proov++;
show_debug_message(string(proov)+" "+string(object_get_name(proov)));
proov++;
show_debug_message(string(proov)+" "+string(object_get_name(proov)));
proov++;
show_debug_message(string(proov)+" "+string(object_get_name(proov)));
proov++;
show_debug_message(string(proov)+" "+string(object_get_name(proov)));
proov++;
show_debug_message(string(proov)+" "+string(object_get_name(proov)));
proov++;
show_debug_message(string(proov)+" "+string(object_get_name(proov)));
proov++;
show_debug_message(string(proov)+" "+string(object_get_name(proov)));
proov++;
show_debug_message(string(proov)+" "+string(object_get_name(proov)));
proov++;
